services:
  db-scauth:
    image: postgres:17.4
    container_name: db-scauth
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - common

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin-scauth
    # Antes de arrancar pgAdmin, crea y chown de los subdirs necesarios:
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"  # http://localhost:8080
    # Before starting pgAdmin, create the required directories and set permissions
    command: >
      bash -c "mkdir -p /var/lib/pgadmin/{storage,sessions} &&
              chown -R pgadmin:pgadmin /var/lib/pgadmin &&
              /entrypoint.sh"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db-scauth
    networks:
      - common

volumes:
  db-data:
  pgadmin-data:

networks:
  common:
    driver: bridge
