#PostgreSQL database :)
services:
  db-scauth:
    image: postgres:latest
    container_name: db-scauth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scauth
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - common

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-scauth
    ports:
      - "8080:80"                # Accede a pgAdmin en http://localhost:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db-scauth
    networks:
      - common

networks:
  common:
    driver: bridge